#!/bin/bash

# Set the input and output file naems
input_file="main.c"
output_file="c"

#Run the C file through the preprocessor and save the result to the output file
gcc -E "$input_file" -o "$output_file"
